# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               nvieirarafael
tagline:             'Difundindo o próprio aprendizado'
description:         'Para consolidar alguns de meus estudos e práticas irei registrar aqui, dicas, tutoriais e explicações que venho aprendendo em meu trabalho e dia a dia.'
url:                 http://nvieirarafael.com
baseurl:             ''
gems: [jekyll-paginate]
paginate:            5
paginate_path: "page:num"

# About/contact
author:
  name:              Rafael Nunes Vieira
  email:             nvieirarafael@gmail.com
  url:

# Custom vars
version:             1.0.0
